# Generated by Django 4.2.5 on 2023-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdle_app', '0003_alter_itemop_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemop',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
