# Generated by Django 4.2.5 on 2023-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdle_app', '0005_alter_itemop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemop',
            name='type',
            field=models.CharField(choices=[('Add', 'Add'), ('Rem', 'Rem')], max_length=3),
        ),
    ]
