# Generated by Django 4.2.5 on 2023-11-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdle_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOp',
            fields=[
                ('hash', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Add', 'Add'), ('Rem', 'Rem')], max_length=3)),
                ('count', models.IntegerField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdle_app.list')),
            ],
        ),
    ]
